repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      # Run the linter on push.
      - id: ruff
        stages: [pre-push]
      # Run the formatter on push.
      - id: ruff-format
        stages: [pre-push]
  - repo: local
    hooks:
      - id: conventional-emojis
        name: Conventional Emojis
        entry: conventional-emojis
        language: python
        stages: [commit-msg]
