repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: conventional-emojis
        name: Conventional Emojis
        entry: conventional-emojis
        language: python
        stages: [commit-msg]
  
